name: flutter_complete_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.8+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  intl: ^0.20.2
  easy_localization: ^3.0.3
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  firebase_core: ^2.30.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
